wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    framework: huggingface
    huggingface_version: 4.11.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.8.11
    start_time: 1683412830
    t:
      1:
      - 1
      - 3
      - 9
      - 11
      2:
      - 1
      - 3
      - 9
      - 11
      3:
      - 7
      - 16
      4: 3.8.11
      5: 0.12.4
      6: 4.11.3
      8:
      - 5
accelerator:
  desc: null
  value: ddp
accumulate_grad_batches:
  desc: null
  value: 1
adam_epsilon:
  desc: null
  value: 1.0e-08
bootstrap_method:
  desc: null
  value: centering
check_val_every_n_epoch:
  desc: null
  value: 100
checkpoint_dir:
  desc: null
  value: checkpoints
clip_range:
  desc: null
  value:
  - -175
  - 250
data_dir:
  desc: null
  value: data/msd/processed/Task06_Lung/
decoder:
  desc: null
  value: upernet
default_root_dir:
  desc: null
  value: .
dropout_rate:
  desc: null
  value: 0.0
encoder:
  desc: null
  value: beit
eval_batch_size:
  desc: null
  value: 2
evaluation:
  desc: null
  value: 1
force_2d:
  desc: null
  value: 0
gpus:
  desc: null
  value: -1
gradient_clip_val:
  desc: null
  value: 1.0
hidden_size:
  desc: null
  value: 768
img_size:
  desc: null
  value:
  - 512
  - 512
  - 5
in_channels:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 3.0e-05
log_every_n_steps:
  desc: null
  value: 1
loss_type:
  desc: null
  value: dicefocal
max_steps:
  desc: null
  value: 25000
mean_std:
  desc: null
  value: null
mlp_dim:
  desc: null
  value: 3072
model_path:
  desc: null
  value: data/bcv/processed/checkpoint/ours/centering/epoch=10-step=12154.ckpt
num_heads:
  desc: null
  value: 12
num_layers:
  desc: null
  value: 12
out_channels:
  desc: null
  value: 14
patch_size:
  desc: null
  value: 16
precision:
  desc: null
  value: 32
save_preds:
  desc: null
  value: false
seed:
  desc: null
  value: 1234
split_json:
  desc: null
  value: dataset_5slices.json
train_batch_size:
  desc: null
  value: 2
use_pretrained:
  desc: null
  value: 1
val_check_interval:
  desc: null
  value: 1.0
warmup_steps:
  desc: null
  value: 20
weight_decay:
  desc: null
  value: 0.05
